apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace = 'com.builttoroam.devicecalendar'
    compileSdk = 34
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    defaultConfig {
        minSdk = 16
        targetSdk = 34
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    
    testOptions {
        unitTests.all {
            useJUnitPlatform()
        }
    }

}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.21"
    implementation 'androidx.annotation:annotation:1.7.1'
    implementation 'com.google.code.gson:gson:2.10.1'
    
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.0'
    testImplementation 'org.mockito:mockito-core:5.7.0'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:5.1.0'
} 
